### PR TITLE
Pass state_info to generators

### PR DESCRIPTION
**Pull request by askpatrickw**
Passing state info to the generators allows us to set the state for the election to the capitalized name.

It also give access to all the other state_info in the generators. I assume we'll use generators for graphics and other things...

### CODE REVIEW

**Comment by askpatrickw** [comment]
OH, it also fixes CSV's too.

**Comment by askpatrickw** [comment]
OOps... I broke the ALL versions.

**Comment by askpatrickw** [comment]
OK... I think this is good now.

I'm not sure about one thing. I have older all-voter.csv where the key looks like `south_carolina/20200229`
and I'm not seeing that even when I build main. It might be you changed this and it is fine, but I'm not sure so pls dbl check.

**Comment by tannewt** [comment]
I may have messed it up. I tweaked the keys a few commits ago.

**Review by tannewt — APPROVED** [review]
Thank you!

**Pull request merged**
