### PR TITLE
Update sc

### PR DESCRIPTION
**Pull request by askpatrickw**
SCVotes let me know our data was incorrect
https://twitter.com/scvotes/status/1313920393892294657

They changed the laws since the data was entered in June.

### CODE REVIEW

**Comment by askpatrickw** [comment]
@tannewt  Should we also delete the tweets which had incorrect dates?

**Comment by tannewt** [comment]
@askpatrickw I can if you like.

**Review by tannewt — APPROVED** [review]
Thanks!

**Comment by askpatrickw** [comment]
@tannewt yeah, I think deleting makes sense in this case. Having an incorrect date linger feels wrong.

**Pull request merged**
