### PR TITLE
Add logo to site pages

### PR DESCRIPTION
**Pull request by askpatrickw**
The site needs a logo that looks like the twitter images. I made a really bad one, but it lays out pretty well on the site.

If someone can make a better resolution image (I cropped this out of the twitter template), the image size is 1021x81. I'd love to put up something else, but for now this would work.

### CODE REVIEW

**Comment by askpatrickw** [comment]
It looks like... 

image

**Comment by tannewt** [comment]
Here are two svgs that should help:

[electioncal_graphics.zip](https://github.com/electioncal/us/files/5185305/electioncal_graphics.zip)

**Comment by askpatrickw** [comment]
Awesome! I'm going to update this with the fullsize logo you provided (just electioncal.us logo no extra stripes) and I'm using one of those favicon generator sites to make all the variants of icon. see:  https://www.favicon-generator.org/

**Comment by askpatrickw** [comment]
image

**Comment by askpatrickw** [comment]
- Logo changes as mentioned
- Favicon as mentioned
- Fix to the Creative Commons logo URL which had a 301 permanent redirect to the new URL.

**Pull request merged**
